--- # ---
# apiVersion: cert-manager.io/v1alpha2
# kind: Issuer
# metadata:
#   name: pesbuk-production
#   namespace: pesbuk-production
# spec:
#   acme:
#     # The ACME server URL
#     server: https://acme-v02.api.letsencrypt.org/directory
#     # Email address used for ACME registration
#     email: gerald.gunasha@gmail.com
#     # Name of a secret used to store the ACME account private key
#     privateKeySecretRef:
#       name: pesbuk-production
#     # Enable the HTTP-01 challenge provider
#     solvers:
#       - selector: {}
#         http01:
#           ingress:
#             class: nginx
apiVersion: v1
kind: Secret
metadata:
  name: pesbuksecret
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASS: bWFzdWthamE=
  DB_HOST: ZGJnZXJhbGQuY3V3d2pweTBsaDY1LmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  DB_NAME: d29yZHByZXNz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pesbuk-production
  namespace: pesbuk-production
spec:
  replicas: 3
  selector:
    matchLabels:
      name: pesbuk-production
  template:
    metadata:
      labels:
        name: pesbuk-production
    spec:
      containers:
        - name: pesbuk-production
          image: vanillavladimir/pesbuk
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: pesbuksecret
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pesbuksecret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: pesbuksecret
                  key: DB_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: pesbuk-production
  namespace: pesbuk-production
spec:
  #type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: pesbuk-production
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pesbuk-production-ingress
  namespace: pesbuk-production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "pesbuk-production"
spec:
  rules:
    - host: pesbuk.production.vladgerald.tech
      http:
        paths:
          #- path: /belajar
          - backend:
              serviceName: pesbuk-production
              servicePort: 80
  tls:
    - hosts:
        - pesbuk.production.vladgerald.tech
      secretName: pesbuk-staging-tls
