env.DOCKER_REGISTRY = 'vanillavladimir'
env.DOCKER_IMAGE_NAME = 'wpadmin'
node('master') {
	// stage('Clean Workspace') {
    //   cleanWs()
    // }
    stage('Git Pull from Github') {
        sh "git clone https://github.com/geraldGhibran/small-project-3-cilsy.git"
    }
    stage('Build Docker Image') {
        sh "cd small-project-3-cilsy/wordpress/apps && docker build --build-arg APP_NAME=wp -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:${BUILD_NUMBER} ."   
    }
    stage('Push Docker Image to Dockerhub') {
        sh "docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:${BUILD_NUMBER}"
    }
    stage('DeployTo Kubernetes Cluster') {
        // sh "kubectl delete namespace wp-production"
        sh "kubectl create namespace wp-production"
        sh "kubectl replace -f small-project-3-cilsy/wordpress/wp-secret.yaml --force -n wp-production"
        sh "kubectl replace -f small-project-3-cilsy/wordpress/wp-production-ssl.yml --force"
        sh'''cd small-project-3-cilsy/wordpress && sed -i "50d" wp-production.yml'''
        sh'''cd small-project-3-cilsy/wordpress && sed -i "49 a \'\\'        image: vanillavladimir/$DOCKER_IMAGE_NAME:${BUILD_NUMBER}" wp-production.yml && sed -i "s/''//" wp-production.yml'''
        sh "cd small-project-3-cilsy/wordpress && kubectl replace -f wp-production.yml --force"
   }
    stage('Remove Docker Image') {
        sh "docker rmi $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:${BUILD_NUMBER}"   
    }
    stage('Clean Workspace') {
      cleanWs()
    }
}