apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: wp-staging
  namespace: wp-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: gerald.gunasha@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: wp-staging
    # Enable the HTTP-01 challenge provider
    solvers:
      - selector: {}
        http01:
          ingress:
            class: nginx
---
apiVersion: v1
kind: Secret
metadata:
  name: wpsecret
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASS: bWFzdWthamE=
  DB_HOST: ZGJnZXJhbGQuY3V3d2pweTBsaDY1LmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  DB_NAME: d29yZHByZXNz
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wp-staging
  namespace: wp-staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wp-staging
  template:
    metadata:
      labels:
        app: wp-staging
    spec:
      containers:
        - name: wp-staging
          image: 978798257904.dkr.ecr.ap-southeast-1.amazonaws.com/wpadmin
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wpsecret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wpsecret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wpsecret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: wpsecret
                  key: DB_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: wp-staging
  namespace: wp-staging
spec:
  #type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: wp-staging
---
# apiVersion: extensions/v1beta1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp-staging-ingress
  namespace: wp-staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "wp-staging"
spec:
  rules:
    - host: wp.staging.vladgerald.tech
      http:
        paths:
          #- path: /belajar
          - backend:
              service:
                name: wp-staging
                port:
                  number: 80
  tls:
    - hosts:
        - wp.staging.vladgerald.tech
      secretName: wp-staging-tls
